appName: "frontend"
namespace: "erp-production"

image:
  repository: hanenall/frontend     
  tag: "f268a7b84637eec646c62aa2c5ec4a1d62e23c7a"
  pullPolicy: IfNotPresent     # pas Always → tag unique 

replicaCount: 2

service:
  port: 80
  targetPort: 80             # nginx écoute sur 80 ✅

resources:
  requests:
    memory: "128Mi"          # frontend plus léger que .NET ✅
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "200m"