appName: "rh"
namespace: "erp-production"

image:
  repository: hanenall/rh
  tag: "ac368465f0cebc723bfbf1b2358592c587d4b300"    
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  port: 80
  targetPort: 80

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

env:
  aspnetcore_environment: "Production"

authentik:
  apiUrl: "http://authentik-server.authentik.svc.cluster.local"

ai:
  defaultProvider: "groq"
  publicBaseUrl: "https://erp.itanis.tn"

interServices:
  crm:       "crm-service"
  projet:    "gestion-projet-service"
  helpdesk:  "helpdesk-service"
  timesheet: "timesheet-service"
  bi:        "bi-service"