apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.db.password }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password }}