apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.namespace }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.env.aspnetcore_environment }}
  ASPNETCORE_URLS: "http://+:{{ .Values.service.targetPort }}"