apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  # .NET lit : ConnectionStrings:DefaultConnection
  # Convention K8s : ConnectionStrings__DefaultConnection (double underscore)
  ConnectionStrings__DefaultConnection: "Server={{ .Values.db.serviceName }}.{{ .Values.db.serviceNamespace }}.svc.cluster.local,{{ .Values.db.port }};Database={{ .Values.db.name }};User Id={{ .Values.db.user }};Password={{ .Values.db.password }};TrustServerCertificate=True"

  # RabbitMQ — selon comment le code .NET le configure
  # à vérifier avec le code des devs (peut nécessiter un autre nom de clé)
  RabbitMQ__Host: "{{ .Values.rabbitmq.serviceName }}.{{ .Values.rabbitmq.serviceNamespace }}.svc.cluster.local"
  RabbitMQ__Port: "{{ .Values.rabbitmq.port }}"
  RabbitMQ__Username: "{{ .Values.rabbitmq.user }}"
  RabbitMQ__Password: "{{ .Values.rabbitmq.password }}"

  # Groq IA
  Groq__ApiKey: "{{ .Values.groq.apiKey }}"