appName: "crm"
namespace: "erp-production"

image:
  repository: nginx      # placeholder ✅
  tag: latest
  pullPolicy: Always
 
replicaCount: 1          # 1 pour tester ✅

service:
  port: 80
  targetPort: 80         # nginx écoute sur 80 ✅

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

env:
  aspnetcore_environment: "Production"
  # indique à .NET dans quel mode tourner
  # Production → optimisations activées
  #            → pages d'erreur détaillées désactivées
  #            → logs minimalistes
  # utilisé dans configmap.yaml →
  # ASPNETCORE_ENVIRONMENT: Production

db:
  name: "db_crm"
  user: "crm_user"
  port: "1433"

rabbitmq:
  port: "5672"
  user: "admin"

interServices:
  rh:        "rh-service"
  projet:    "gestion-projet-service"
  helpdesk:  "helpdesk-service"
  timesheet: "timesheet-service"
  bi:        "bi-service"