appName: "crm"
namespace: "erp-production"

image:
  repository: hanenall/crm
  tag: "811cdf91b11f8fdc836faae66fea08a7e34ec0f6"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  port: 80
  targetPort: 80

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

env:
  aspnetcore_environment: "Production"

authentik:
  apiUrl: "http://authentik-server.authentik.svc.cluster.local"

interServices:
  rh:        "rh-service"
  projet:    "gestion-projet-service"
  helpdesk:  "helpdesk-service"
  timesheet: "timesheet-service"
  bi:        "bi-service"

serviceAccount:
  create: true