apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.namespace }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.env.aspnetcore_environment }}
  ASPNETCORE_URLS: "http://+:{{ .Values.service.targetPort }}"

  AUTHENTIK_API_URL: {{ .Values.authentik.apiUrl }}

  RH_SERVICE_URL:        "http://{{ .Values.interServices.rh }}.{{ .Values.namespace }}.svc.cluster.local"
  PROJET_SERVICE_URL:    "http://{{ .Values.interServices.projet }}.{{ .Values.namespace }}.svc.cluster.local"
  CRM_SERVICE_URL:       "http://{{ .Values.interServices.crm }}.{{ .Values.namespace }}.svc.cluster.local"
  TIMESHEET_SERVICE_URL: "http://{{ .Values.interServices.timesheet }}.{{ .Values.namespace }}.svc.cluster.local"
  BI_SERVICE_URL:        "http://{{ .Values.interServices.bi }}.{{ .Values.namespace }}.svc.cluster.local"
