namespace: "erp-production"

ingress:
  host: "erp.itanis.tn"
  className: "nginx"

authentik:
  namespace: "authentik"
  serviceName: "ak-outpost-erp-outpost"
  port: "9000"
  publicHost: "erp.itanis.tn"

services:
  frontend:
    name: "frontend-service" 
    port: 80
  crm:
    name: "crm-service"
    port: 80
  rh:
    name: "rh-service"
    port: 80
  bi:
    name: "bi-service"
    port: 80
  projet:
    name: "gestion-projet-service"
    port: 80
  helpdesk:
    name: "helpdesk-service"
    port: 80
  timesheet:
    name: "timesheet-service"
    port: 80

devops:
  argocd:
    name: "argocd-server"
    port: 80
    namespace: "argocd"
    host: "argocd.itanis.tn"
  grafana:
    name: "grafana"
    port: 80
    namespace: "monitoring"
    host: "grafana.itanis.tn"
  kibana:
    name: "kibana-kibana"
    port: 5601
    namespace: "monitoring"
    host: "kibana.itanis.tn"
  authentik:
    name: "authentik-server"
    port: 80
    host: "authentik.itanis.tn"
  rabbitmq:
    name: "rabbitmq-nodeport"
    port: 15672
    host: "rabbitmq.itanis.tn"