apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  # Grafana et Kibana sont dans le même namespace monitoring
  # → un seul fichier ingress pour les deux ✅
  namespace: {{ .Values.devops.grafana.namespace }}   # → monitoring
spec:
  ingressClassName: {{ .Values.ingress.className }}   # → nginx
  rules:
    # grafana.itanis.tn → service Grafana
    - host: {{ .Values.devops.grafana.host }}         # → grafana.itanis.tn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.devops.grafana.name }}      # → grafana
                port:
                  number: {{ .Values.devops.grafana.port }}  # → 80

    # kibana.itanis.tn → service Kibana
    - host: {{ .Values.devops.kibana.host }}          # → kibana.itanis.tn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.devops.kibana.name }}      # → kibana-kibana
                port:
                  number: {{ .Values.devops.kibana.port }}  # → 5601