apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  # RabbitMQ est dans erp-production
  # → utilise .Values.namespace ✅ pas de duplication
  namespace: {{ .Values.namespace }}                  # → erp-production
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuer }}   # → letsencrypt-prod
spec:
  ingressClassName: {{ .Values.ingress.className }}   # → nginx
  tls:
    - hosts:
        - {{ .Values.devops.rabbitmq.host }}          # → rabbitmq.itanis.tn
      secretName: rabbitmq-itanis-tls                 # cert-manager le crée
  rules:
    # rabbitmq.itanis.tn → interface admin RabbitMQ
    - host: {{ .Values.devops.rabbitmq.host }}        # → rabbitmq.itanis.tn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.devops.rabbitmq.name }}      # → rabbitmq
                port:
                  # port 15672 → interface admin RabbitMQ
                  number: {{ .Values.devops.rabbitmq.port }}  # → 15672