apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: erp-ingress
  namespace: {{ .Values.namespace }}    # → erp-production
  annotations:
    # rewrite-target : retire le préfixe /api/module avant d'envoyer au pod
    # $2 = 2ème groupe de capture du regex
    # exemple : /api/crm/clients → pod reçoit /clients
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuer }}

    # auth-url : Nginx interroge Authentik avant chaque requête
    # si non connecté → Authentik retourne 401 → redirection login
    nginx.ingress.kubernetes.io/auth-url: "http://{{ .Values.authentik.serviceName }}.{{ .Values.authentik.namespace }}.svc.cluster.local:{{ .Values.authentik.port }}/outpost.goauthentik.io/auth/nginx"

    # auth-signin : URL page login Authentik
    # $escaped_request_uri → redirige vers page demandée après login
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.authentik.publicHost }}/outpost.goauthentik.io/start?rd=$escaped_request_uri"
    # headers envoyés au frontend après authentification réussie
    # X-authentik-username → nom utilisateur
    # X-authentik-groups   → groupes (ceo, rh_manager...)
    # X-authentik-email    → email utilisateur
    # → frontend React lit X-authentik-groups
    #   pour afficher les bons boutons ✅
    nginx.ingress.kubernetes.io/auth-response-headers: "X-authentik-username,X-authentik-groups,X-authentik-email"

spec:
  # remplace l'annotation dépréciée kubernetes.io/ingress.class ✅
  ingressClassName: {{ .Values.ingress.className }}
  tls:                                                                  # ← AJOUT
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: erp-itanis-tls
  rules:
    - host: {{ .Values.ingress.host }}    # → erp.itanis.tn
      http:
        paths:
          # ImplementationSpecific obligatoire avec regex ✅
          # groupe 1 : (/|$) → slash ou fin de chaîne
          # groupe 2 : (.*) → ce qui suit → utilisé par rewrite-target
          # exemple : /api/crm/clients → $2=clients → pod reçoit /clients

          - path: /api/crm(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.services.crm.name }}     # → crm-service
                port:
                  number: {{ .Values.services.crm.port }} # → 80

          - path: /api/rh(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.services.rh.name }}      # → rh-service
                port:
                  number: {{ .Values.services.rh.port }}  # → 80

          - path: /api/bi(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.services.bi.name }}      # → bi-service
                port:
                  number: {{ .Values.services.bi.port }}  # → 80

          - path: /api/projet(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.services.projet.name }}      # → gestion-projet-service
                port:
                  number: {{ .Values.services.projet.port }}  # → 80

          - path: /api/helpdesk(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.services.helpdesk.name }}      # → helpdesk-service
                port:
                  number: {{ .Values.services.helpdesk.port }}  # → 80

          - path: /api/timesheet(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.services.timesheet.name }}      # → timesheet-service
                port:
                  number: {{ .Values.services.timesheet.port }}  # → 80

          # catch-all → tout ce qui ne commence pas par /api/
          # → redirigé vers le frontend React
          # DOIT être en dernier sinon intercepte tout ❌
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.services.frontend.name }}      # → frontend-service
                port:
                  number: {{ .Values.services.frontend.port }}  # → 80