appName: "timesheet"
namespace: "erp-production"

image:
  repository: hanenall/timesheet
  tag: "624bfff924b3f537ae9a7aa0af3613db61029208"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  port: 80
  targetPort: 80

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

env:
  aspnetcore_environment: "Production"

authentik:
  apiUrl: "http://authentik-server.authentik.svc.cluster.local"

interServices:
  rh:        "rh-service"
  projet:    "gestion-projet-service"
  helpdesk:  "helpdesk-service"
  crm:       "crm-service"
  bi:        "bi-service"

serviceAccount:
  create: true